DROP TABLE IF EXISTS 
    LESSON_CHECKPOINT,
    ATTEMPT,
    PROG_TASK,
    ANSWER_VARIANT,
    QUIZ_TASK,
    TEST_LESSON,
    VIDEO_LESSON,
    TEXT_LESSON_BLOCK,
    TEXT_LESSON,
    LESSON_BUCKET,
    COMMENTS,
    DISCUSSION,
    LESSON,
    PART,
    COURSE_METRIK,
    TAGS,
    VALID_TAGS,
    COURSE,
    SESSIONS,
    USERTABLE
CASCADE;

CREATE TABLE USERTABLE (
    ID BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    Email TEXT UNIQUE CHECK (length(Email) BETWEEN 6 AND 64) NOT NULL,
    Password TEXT NOT NULL,
    Salt TEXT CHECK (LENGTH(salt) BETWEEN 8 AND 200) NOT NULL,
    Name TEXT CHECK (length(Name) BETWEEN 2 AND 32) NOT NULL,
    Bio TEXT CHECK (length(Bio) <= 20000),
    hide_email BOOLEAN NOT NULL DEFAULT FALSE,
    Avatar_src TEXT DEFAULT 'path_to_default',
    Created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    Updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE SESSIONS (
    ID BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    User_ID BIGINT NOT NULL,
    Token TEXT UNIQUE NOT NULL,
    Expire TIMESTAMP NOT NULL,
    Created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    Updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (User_ID) REFERENCES USERTABLE(ID) ON DELETE CASCADE,
    UNIQUE(User_ID, Token)
);

CREATE TABLE COURSE (
    ID BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    Creator_User_ID BIGINT NOT NULL,
    Title TEXT CHECK (length(Title) BETWEEN 2 AND 32),
    Description TEXT NOT NULL CHECK (length(Description) <= 2000),
    Avatar_src TEXT NOT NULL DEFAULT 'path_to_default',
    Price INT NOT NULL DEFAULT 0,
    Purchases_amount INT NOT NULL DEFAULT 0,
    Time_to_pass INT NOT NULL CHECK (Time_to_pass BETWEEN 20 AND 10000),
    Created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    Updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (Creator_User_ID) REFERENCES USERTABLE(ID) ON DELETE CASCADE,
    UNIQUE(Creator_User_ID, Title)
);

CREATE TABLE VALID_TAGS (
    ID BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    Title TEXT UNIQUE NOT NULL CHECK (length(Title) BETWEEN 2 AND 32),
    Created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    Updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE TAGS (
    ID BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    Tag_ID BIGINT NOT NULL REFERENCES VALID_TAGS(ID) ON DELETE CASCADE,
    Course_ID BIGINT NOT NULL REFERENCES COURSE(ID) ON DELETE CASCADE,
    Created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    Updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (Course_ID, Tag_ID)
);

CREATE TABLE COURSE_METRIK (
    ID BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    Course_ID BIGINT NOT NULL REFERENCES COURSE(ID) ON DELETE CASCADE,
    User_ID BIGINT NOT NULL REFERENCES USERTABLE(ID) ON DELETE CASCADE,
    Rating INT NOT NULL DEFAULT 0 CHECK (Rating BETWEEN 1 AND 5),
    Created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    Updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (Course_ID, User_ID)
);


CREATE TABLE PART (
    ID BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    Course_ID BIGINT NOT NULL,
    Part_Order INT NOT NULL,
    Title TEXT CHECK (length(Title) BETWEEN 2 AND 32),
    Created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    Updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (Course_ID) REFERENCES COURSE(ID) ON DELETE CASCADE,
    UNIQUE (Course_ID, Part_Order)
);

CREATE TABLE LESSON_BUCKET (
    ID BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    Part_ID BIGINT NOT NULL REFERENCES PART(ID) ON DELETE CASCADE,
    Lesson_Bucket_Order INT NOT NULL,
    Title TEXT CHECK (length(Title) BETWEEN 2 AND 32),
    Created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    Updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (Part_ID, Lesson_Bucket_Order)
);

CREATE TABLE LESSON (
    ID BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    Lesson_Bucket_ID BIGINT NOT NULL REFERENCES LESSON_BUCKET(ID) ON DELETE CASCADE,
    Lesson_Order INT NOT NULL,
    Title TEXT CHECK (length(Title) BETWEEN 2 AND 32),
    Created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    Updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (Lesson_Bucket_ID, Lesson_Order)
);

CREATE TABLE DISCUSSION (
    ID BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    Lesson_ID BIGINT NOT NULL REFERENCES LESSON(ID) ON DELETE CASCADE,
    Author_ID BIGINT NOT NULL REFERENCES USERTABLE(ID) ON DELETE CASCADE,
    Body TEXT NOT NULL CHECK (length(Body) BETWEEN 12 AND 2000),
    Created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    Updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE COMMENTS (
    ID BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    Lesson_ID BIGINT NOT NULL REFERENCES LESSON(ID) ON DELETE CASCADE,
    Author_ID BIGINT NOT NULL REFERENCES USERTABLE(ID) ON DELETE CASCADE,
    Body TEXT NOT NULL CHECK (length(Body) BETWEEN 12 AND 2000),
    Created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    Updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);


CREATE TABLE TEXT_LESSON (
    ID BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    Lesson_ID BIGINT NOT NULL,
    Created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    Updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (Lesson_ID) REFERENCES LESSON(ID) ON DELETE CASCADE
);

CREATE TABLE TEXT_LESSON_BLOCK (
    ID BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    Text_Lesson_ID BIGINT NOT NULL,
    Value TEXT NOT NULL,
    Is_Image BOOLEAN NOT NULL,
    Text_Lesson_Block_Order INT NOT NULL,
    Created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    Updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (Text_Lesson_ID) REFERENCES TEXT_LESSON(ID) ON DELETE CASCADE,
    UNIQUE (Text_Lesson_ID, Text_Lesson_Block_Order)
);

CREATE TABLE VIDEO_LESSON (
    ID BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    Lesson_ID BIGINT NOT NULL,
    Video_src TEXT NOT NULL,
    Created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    Updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (Lesson_ID) REFERENCES LESSON(ID) ON DELETE CASCADE
);

CREATE TABLE TEST_LESSON (
    ID BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    Lesson_ID BIGINT NOT NULL REFERENCES LESSON(ID) ON DELETE CASCADE,
    Created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    Updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE QUIZ_TASK (
    ID BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    Lesson_Test_ID BIGINT NOT NULL REFERENCES TEST_LESSON(ID) ON DELETE CASCADE,
    Question TEXT NOT NULL CHECK (length(Question) BETWEEN 8 AND 64),
    Created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    Updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(Lesson_Test_ID, Question)
);

CREATE TABLE ANSWER_VARIANT (
    ID BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    Quiz_Task_ID BIGINT NOT NULL,
    Answer TEXT NOT NULL CHECK (LENGTH(Answer) BETWEEN 2 AND 256), 
    Is_True BOOLEAN NOT NULL,
    Created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    Updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (Quiz_Task_ID) REFERENCES QUIZ_TASK(ID) ON DELETE CASCADE,
    UNIQUE(Quiz_Task_ID, Answer)
);

CREATE TABLE PROG_TASK (
    ID BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    Lesson_Test_ID BIGINT NOT NULL REFERENCES TEST_LESSON(ID) ON DELETE CASCADE,
    Description TEXT NOT NULL CHECK (length(Description) BETWEEN 8 AND 2000),
    Input_Data TEXT NOT NULL CHECK (length(Input_Data) BETWEEN 8 AND 500),
    Output_Data TEXT NOT NULL CHECK (length(Output_Data) BETWEEN 8 AND 500),
    Created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    Updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE ATTEMPT (
    ID BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    Prog_Task_ID BIGINT,
    User_ID BIGINT,
    Src TEXT NOT NULL,
    Status TEXT CHECK (Status IN ('Pending', 'Failed', 'Passed')),
    Created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    Updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (Prog_Task_ID) REFERENCES PROG_TASK(ID) ON DELETE CASCADE,
    FOREIGN KEY (User_ID) REFERENCES USERTABLE(ID) ON DELETE CASCADE,
    UNIQUE(Prog_Task_ID, User_ID, Src)
);

CREATE TABLE LESSON_CHECKPOINT (
    ID BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    User_ID BIGINT NOT NULL REFERENCES USERTABLE(ID) ON DELETE CASCADE,
    Lesson_ID BIGINT NOT NULL REFERENCES LESSON(ID) ON DELETE CASCADE,
    Created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    Updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
