# Dockerfile.golangci-lint
FROM golang:1.23

WORKDIR /app

# Копируем go.mod и go.sum для кеша зависимостей
COPY go.mod go.sum ./

# Загружаем модули (кешируем)
RUN go mod download

# Копируем все файлы сервиса
COPY . .

# Устанавливаем golangci-lint
RUN go install github.com/golangci/golangci-lint/cmd/golangci-lint@v1.55.2

ENTRYPOINT ["golangci-lint", "run"]
