global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'main-service'
    static_configs:
      - targets: ['main-service:8080']

  - job_name: 'user-service'
    static_configs:
      - targets: ['user-service:8081']

  - job_name: 'course-service'
    static_configs:
      - targets: ['course-service:8082']

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
