name: Run golangci-lint

on:
  push:
    branches: [ "main", "master", "microservices" ]
  pull_request:
    branches: [ "main", "master", "microservices" ]

jobs:
  lint-all:
    name: Lint All Services
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Build custom golangci-lint image with Go 1.23
        run: |
          docker build -f .github/docker/golangci-lint-go123.Dockerfile -t custom-golangci-lint .

      - name: Run linters
        run: |
          services=(
            "SkillForceBillingService"
            "SkillForceCourseService"
            "SkillForceMailService"
            "SkillForceMainService"
            "SkillForceUserService"
          )

          for service in "${services[@]}"; do
            if [ -d "$service" ]; then
              echo "🔍 Linting $service"
              docker run --rm \
                -v "$(pwd)/$service:/app" \
                -w /app \
                custom-golangci-lint \
                golangci-lint run ./...
            else
              echo "⚠️ Warning: Directory $service not found"
            fi
          done
