name: Run golangci-lint (Docker)

on:
  push:
    branches: [ "main", "master", "microservices" ]
  pull_request:
    branches: [ "main", "master", "microservices" ]

jobs:
  lint-all:
    name: Lint All Services (Docker)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run golangci-lint via Docker
        run: |
          services=(
            "SkillForceBillingService"
            "SkillForceCourseService"
            "SkillForceMailService"
            "SkillForceMainService"
            "SkillForceUserService"
          )

          for service in "${services[@]}"; do
            if [ -d "$service" ]; then
              echo "🔍 Linting $service"
              docker run --rm -v $(pwd)/$service:/app -w /app \
                golangci/golangci-lint:v1.55.2 \
                golangci-lint run --timeout=5m
            else
              echo "⚠️ Warning: Directory $service not found"
            fi
          done
