name: Run golangci-lint

on:
  push:
    branches: [ "main", "master", "microservices" ]
  pull_request:
    branches: [ "main", "master", "microservices" ]

jobs:
  lint-services:
    name: Lint Services
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [
          "SkillForceBillingService",
          "SkillForceCourseService",
          "SkillForceMailService",
          "SkillForceMainService",
          "SkillForceUserService"
        ]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23.0'
      - name: Run golangci-lint for ${{ matrix.service }}
        working-directory: ${{ matrix.service }}
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.55
          args: --timeout=5m