name: Run golangci-lint

on:
  push:
    branches: [ "main", "master", "microservices" ]
  pull_request:
    branches: [ "main", "master", "microservices" ]

jobs:
  lint-all:
    name: Lint All Services
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Build custom golangci-lint image
        run: docker build -t custom-golangci-lint:1.23 .

      - name: Run linters
        run: |
          services=(
            "SkillForceBillingService"
            "SkillForceCourseService"
            "SkillForceMailService"
            "SkillForceMainService"
            "SkillForceUserService"
          )

          for service in "${services[@]}"; do
            if [ -d "$service" ]; then
              echo "Checking $service"
              docker run --rm \
                -v "${{ github.workspace }}/$service:/app" \
                -w /app \
                custom-golangci-lint:1.23 \
                run ./...
            else
              echo "Warning: Directory $service not found"
            fi
          done
