name: Run golangci-lint

on:
  push:
    branches: [ "main", "master", "microservices" ]
  pull_request:
    branches: [ "main", "master", "microservices" ]

jobs:
  lint-all:
    name: Lint All Services
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23.0'
      
      - name: Install golangci-lint
        run: |
          curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.55.2
      
      - name: Run linters
        run: |
          services=(
            "SkillForceBillingService"
            "SkillForceCourseService"
            "SkillForceMailService"
            "SkillForceMainService"
            "SkillForceUserService"
          )
          
          for service in "${services[@]}"; do
            if [ -d "$service" ]; then
              echo "Checking $service"
              cd "$service" && $(go env GOPATH)/bin/golangci-lint run ./... && cd ..
            else
              echo "Warning: Directory $service not found"
            fi
          done