name: Run golangci-lint

on:
  push:
    branches: [ "main", "master", "microservices" ]
  pull_request:
    branches: [ "main", "master", "microservices" ]

jobs:
  lint-all:
    name: Lint All Services
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Set up Go 1.23.0
        uses: actions/setup-go@v4
        with:
          go-version: '1.23.0'

      - name: Show Go version
        run: go version
      
      - name: Install golangci-lint
        run: |
          curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh \
            | sh -s -- -b $(go env GOPATH)/bin v1.55.2
          
      - name: Show golangci-lint version
        run: $(go env GOPATH)/bin/golangci-lint --version

      - name: Run linters for all services
        run: |
          services=(
            "SkillForceBillingService"
            "SkillForceCourseService"
            "SkillForceMailService"
            "SkillForceMainService"
            "SkillForceUserService"
          )

          for service in "${services[@]}"; do
            if [ -d "$service" ]; then
              echo "🔍 Linting $service"
              cd "$service"

              # Optional: temporarily remove toolchain line if needed
              if grep -q '^toolchain ' go.mod; then
                echo "⚠️ Removing 'toolchain' line temporarily for linters"
                sed -i '/^toolchain /d' go.mod
              fi

              $(go env GOPATH)/bin/golangci-lint run ./...
              cd ..
            else
              echo "⚠️ Warning: Directory $service not found"
            fi
          done
